### PR TITLE
Updated Solidity compiler directive to version to 0.4.15

### PR DESCRIPTION
**Pull request by lbeder**
I've updated the Solidity compiler directive to version to 0.4.15, since this is the latest version used by `truffle`, and fixed all of the compilation warnings.

### CODE REVIEW

**Comment by lbeder** [comment]
I've upgraded to 0.4.15.

**Comment by oryband** [comment]
Hey, can we get this merged? this pr has been waiting for two weeks.

Thanks!

**Comment by doodyparizada** [comment]
This could be very helpful. Please merge!

**Comment by fuzzyami** [comment]
oh hai! can you please has merge-burger? thanks!

**Comment by cag** [comment]
LGTM 👍

**Comment by denisgranha** [comment]
hey @lbeder thanks for your time, please check out the new repo https://github.com/gnosis/MultiSigWallet we moved it to the Gnosis organization

**Pull request closed without merging**
